source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JHColorPickerController_Example', :exclusive => true do
  pod "JHColorPickerController", :path => "../"
end

target 'JHColorPickerController_Tests', :exclusive => true do
  pod "JHColorPickerController", :path => "../"

  
end
